# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'kittenTricks' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kittenTricks
  pod 'AppCenter/Push', '~> 1.0.1'
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

end
